version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "19000:19000" # Expo server
      - "19001:19001" # Expo LAN
      - "19002:19002" # Expo Tunnel
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=frontend
      - API_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
